export const heroStats = [
  { n: '150+', l: 'Pacientes' },
  { n: 'Lab Propio', l: 'Analitos' },
  { n: 'Ley 27.357', l: 'Marco Legal' },
];

export const panelConfig = [
  {
    tag: 'Paciente Dispensado',
    tagCls: 'bg-lime-400/10 border-lime-400/20 text-lime-300',
    title: 'Medicina garantizada',
    hl: 'sin cultivar',
    end: '',
    desc: 'Por $300.000 al mes recibís 40 gramos de genéticas analizadas en laboratorio, con REPROCAN gestionado por nuestra ONG y acompañamiento médico continuo.',
    chips: ['40g/mes', 'REPROCAN', 'Médico', 'Legal'],
    chipCls: 'bg-lime-400/10 text-lime-300 border-lime-400/20',
    glow: 'rgba(163,230,53,0.2)',
    orbColor: 'rgba(163,230,53,0.12)',
    orbColor2: 'rgba(34,197,94,0.08)',
    bgImage: '/images/bg/cultivo.jpg',
  },
  {
    tag: 'Cultivador Solidario',
    tagCls: 'bg-emerald-400/10 border-emerald-400/20 text-emerald-300',
    title: 'Tu patio, ',
    hl: '4 pacientes',
    end: '',
    desc: 'Por $500.000 al mes te instalamos un indoor completo de 4 líneas (9 plantas cada una). 1 línea para vos y 3 para la red solidaria de pacientes de Citronella.',
    chips: ['Indoor incluido', '4 líneas', 'Solidario', 'Sin inversión'],
    chipCls: 'bg-emerald-400/10 text-emerald-300 border-emerald-400/20',
    glow: 'rgba(16,185,129,0.2)',
    orbColor: 'rgba(6,182,212,0.1)',
    orbColor2: 'rgba(16,185,129,0.08)',
    bgImage: '/images/bg/market.jpg',
  },
  {
    tag: 'Investigación Científica',
    tagCls: 'bg-amber-400/10 border-amber-400/20 text-amber-300',
    title: 'Ciencia que ',
    hl: 'salva vidas',
    end: '',
    desc: 'Cada membresía financia ensayos clínicos propios en patologías neurodegenerativas como el Parkinson. Nuestro laboratorio de analitos garantiza pureza y trazabilidad.',
    chips: ['Parkinson', 'Analitos', 'Trazabilidad', 'Ciencia'],
    chipCls: 'bg-amber-400/10 text-amber-300 border-amber-400/20',
    glow: 'rgba(251,191,36,0.15)',
    orbColor: 'rgba(251,191,36,0.08)',
    orbColor2: 'rgba(245,158,11,0.05)',
    bgImage: '/images/bg/community.jpg',
  },
];

export const features = [
  {
    icon: '⚖️',
    title: 'Gestión REPROCAN',
    desc: 'Trámites legales simplificados. Nuestro equipo administrativo gestiona tu credencial para que cumplas con la Ley 27.357 sin preocupaciones.',
    gradient: 'from-lime-300 to-green-600',
    glow: 'rgba(163,230,53,0.3)',
    border: 'border-lime-400/15 hover:border-lime-400/40',
    bg: 'bg-lime-400/10 group-hover:bg-lime-400/25',
  },
  {
    icon: '🔬',
    title: 'Laboratorio de Analitos',
    desc: 'Cada genética es analizada en nuestro laboratorio propio. Pureza verificada científicamente, sin sorpresas ni productos del mercado negro.',
    gradient: 'from-emerald-300 to-teal-600',
    glow: 'rgba(16,185,129,0.3)',
    border: 'border-emerald-400/15 hover:border-emerald-400/40',
    bg: 'bg-emerald-400/10 group-hover:bg-emerald-400/25',
  },
  {
    icon: '🤝',
    title: 'Red Solidaria',
    desc: 'Sos parte de una comunidad donde cada cultivador alimenta a pacientes que no pueden hacerlo solos. Tu patio transformado en polo medicinal.',
    gradient: 'from-cyan-300 to-blue-600',
    glow: 'rgba(6,182,212,0.3)',
    border: 'border-cyan-400/15 hover:border-cyan-400/40',
    bg: 'bg-cyan-400/10 group-hover:bg-cyan-400/25',
  },
  {
    icon: '👨‍⚕️',
    title: 'Acompañamiento Médico',
    desc: 'Seguimiento clínico continuo con profesionales que ajustan tu tratamiento según evolución. No te quedás solo con un frasco y una indicación.',
    gradient: 'from-violet-300 to-purple-600',
    glow: 'rgba(139,92,246,0.3)',
    border: 'border-violet-400/15 hover:border-violet-400/40',
    bg: 'bg-violet-400/10 group-hover:bg-violet-400/25',
  },
  {
    icon: '💰',
    title: 'Membresía Transparente',
    desc: 'Sabés exactamente dónde va cada peso. $300k como paciente dispensado o $500k como cultivador solidario. Sin costos ocultos ni sorpresas.',
    gradient: 'from-amber-300 to-orange-600',
    glow: 'rgba(251,191,36,0.3)',
    border: 'border-amber-400/15 hover:border-amber-400/40',
    bg: 'bg-amber-400/10 group-hover:bg-amber-400/25',
  },
  {
    icon: '🏛️',
    title: 'Sede Física en Córdoba',
    desc: 'Nos encontramos en 9 de Julio 1196, Córdoba Capital. Atendimiento presencial con equipo humano que escucha tu caso sin apuro.',
    gradient: 'from-rose-300 to-pink-600',
    glow: 'rgba(244,63,94,0.3)',
    border: 'border-rose-400/15 hover:border-rose-400/40',
    bg: 'bg-rose-400/10 group-hover:bg-rose-400/25',
  },
];

export const marketItems = [
  { name: 'Paciente Dispensado', price: '$300k/mes', r: 4.8, e: '💊', s: '150+' },
  { name: 'Cultivador Solidario', price: '$500k/mes', r: 4.9, e: '🌿', s: '150+' },
  { name: 'Laboratorio Analitos', price: 'Incluido', r: 5.0, e: '🔬', s: '24/7' },
  { name: 'Gestión REPROCAN', price: 'Incluido', r: 4.7, e: '⚖️', s: '100%' },
  { name: 'Acompañamiento Médico', price: 'Incluido', r: 4.8, e: '👨‍⚕️', s: 'Continuo' },
  { name: 'Red Solidaria', price: 'Incluido', r: 4.9, e: '🤝', s: '450 personas' },
];

export const communityPosts = [
  {
    a: 'Dr. Fernández',
    av: '👨‍⚕️',
    t: '1d',
    title: 'Nuevo ensayo clínico en Parkinson',
    c: 'Los resultados preliminares de nuestro protocolo con cannabinoides específicos muestran mejoras notables en la calidad de vida de los pacientes.',
    l: 48,
    cm: 23,
    tag: 'Investigación',
    tc: 'text-lime-400 bg-lime-400/10',
  },
  {
    a: 'María C.',
    av: '👩‍🌾',
    t: '2d',
    title: 'Mi experiencia como cultivadora solidaria',
    c: 'Nunca imaginé que mi patio podía cambiar la vida de otras personas. Citronella me instaló todo y ahora 4 pacientes reciben su medicina mensual.',
    l: 35,
    cm: 14,
    tag: 'Testimonio',
    tc: 'text-emerald-400 bg-emerald-400/10',
  },
  {
    a: 'Carlos M.',
    av: '🧑',
    t: '3d',
    title: 'Dejé el mercado negro hace 6 meses',
    c: 'La tranquilidad de saber que mi medicina está analizada en laboratorio y respaldada por la Ley 27.357 no tiene precio.',
    l: 52,
    cm: 31,
    tag: 'Historia',
    tc: 'text-amber-400 bg-amber-400/10',
  },
];

export const ecosystemWords = [
  'Medicinal',
  'Legal',
  'Solidario',
  'Laboratorio',
  'REPROCAN',
  'Ciencia',
  'Comunidad',
  'Investigación',
];
